GENESIS-52 Sales-Order: FO (Framework Order) - new fields
OpusCapita/sales-order pull request #124
Opened 2020-10-15 09:20 UTC by ElaCzapiewska

changes related to limit order implementation.
new fields added to SalesOrder: orderType, ValidityPeriodStartDate, ValidityPeriodEndDate.
new fields added to SalesOrderItem: itemType, limitValue.
orderType "replaces" isService field that was able to differentiate between 2 order types.
itemType is required as limitOrder can consist of different types of items.
changes made in the code should assure proper behavior of different order types.

2020-10-15 13:47 UTC, nczeranka requested changes
General question/comments:
- has there been a meeting with Silviya to clarify the open questions? If not: how was the decision made for developing?
- I'ld prefer to keep the branch name shorter, e.g. only the feature/<ticket no>. But that's personal flavor.
- We need a documentation as part of the github repository that explains the flow for the different SO types - including the statuses! E.g. in the SalesOrder Readme.md
- Add only translations for English and languages that you are speaking perfectly. Leave the rest for native speaker or professionals. (We are always using a fallback to English, if the translation for the selected language is missing!)
- Don't add fields as non-nullable if they are used only for a specific use cases. (e.g. validityPeriod*, ...)
- Try to keep it simple and do clearly distinctions between the use cases.

2020-10-15 13:47 UTC, nczeranka commented on src/client/api/DespatchAdvice.js
> +                .map(item => {
What about the fallback for existing SalesOrderItems?
You have to do either a migration of the complete data set or add a compatibility layer that acts as it was before introducing the itemType field. I'ld prefer the compatibility layer, if it won't get too complex.

2020-10-15 13:47 UTC, nczeranka commented on src/client/api/DespatchAdvice.js
> +const ITEM = salesOrderTypes.itemType.item;
I'ld prefer a clear name. E.g. "standard" -> to be discussed with PM (Vesa).

2020-10-15 13:47 UTC, nczeranka commented on src/client/components/SalesOrderEdit/SalesOrderEditItems.react.js
> +        const isLimitOrder = salesOrder.orderType === LIMIT_ORDER;
Does not exist for old SalesOrders. Fallback is needed.

2020-10-15 13:47 UTC, nczeranka commented on src/client/components/SalesOrderEdit/SalesOrderEditItems.react.js
> +                        }
Is the layout discussed with our PM (Vesa). I am not happy with adding another column (width > 100%)

2020-10-15 13:47 UTC, nczeranka commented on src/client/components/SalesOrderEdit/SalesOrderEditItems.react.js
> +                            const isServiceItem = item.itemType === SERVICE_ITEM;
Fallback to old SalesOrderItems that misses those fields is missing.

2020-10-15 13:47 UTC, nczeranka commented on src/client/components/SalesOrderEdit/SalesOrderEditItems.react.js
> +                                        </span>
Do we properly handle the status for LimitItems in the rest of the code?

2020-10-15 13:47 UTC, nczeranka commented on src/client/components/SalesOrderEdit/SalesOrderValidate.js
> +    return (attributes.limitValue && attributes.confirmedTotalNetPrice > attributes.limitValue) ? options.message : null;
Don't get it. Where is it used and what is the purpose?
I guess it is about the call-off value: it is not allowed to invoice a higher value than the limit.
In this case a few comments/questions:
* Are you storing the call-off value in confirmedTotalNetPrice? Don't do this. As you see, it is hard to read and to maintain.
* when is this test executed?
* what is the resulting action for the user?
* Isn't this check to be planned for the SalesInvoice editor after a flip from LimitItems?

2020-10-15 13:47 UTC, nczeranka commented on src/client/components/SalesOrderEdit/i18n/de.json
> +    "SalesOrderEditForm.label.lineItems.validityPeriodEndDate": "Gültigkeitszeitraum Enddatum",
Smaller option "Gültig bis" (is is full already)

2020-10-15 14:27 UTC, ElaCzapiewska commented on src/client/api/DespatchAdvice.js
> +                .map(item => {
Vesa had a meeting with Silviya and clarified the open questions in the jira task.
I will leave only English translations.
As to fallback on existing orders/items - the commit contains migration script with updates on the existing data

2020-10-15 14:29 UTC, ElaCzapiewska commented on src/client/api/DespatchAdvice.js
> +const ITEM = salesOrderTypes.itemType.item;
today, we have "order" and "serviceOrder", that is why "order", "serviceOrder", "limitOrder", "item", "serviceItem", "limitItem" have been used

2020-10-15 14:37 UTC, ElaCzapiewska commented on src/client/components/SalesOrderEdit/SalesOrderEditItems.react.js
> +                        }
layout was presented to Vesa, without details on column with however

2020-10-15 14:37 UTC, ElaCzapiewska commented on src/client/components/SalesOrderEdit/SalesOrderEditItems.react.js
> +                            const isServiceItem = item.itemType === SERVICE_ITEM;
the commit contains migration script with updates on the existing data

2020-10-15 14:43 UTC, ElaCzapiewska commented on src/client/components/SalesOrderEdit/SalesOrderEditItems.react.js
> +                                        </span>
I think so, we handle only confirmation and billing status for limit items, and it is implemented in the code

2020-10-15 14:54 UTC, ElaCzapiewska commented on src/client/components/SalesOrderEdit/SalesOrderValidate.js
> +    return (attributes.limitValue && attributes.confirmedTotalNetPrice > attributes.limitValue) ? options.message : null;
this validation is not related to invoicing, it is used during order confirmation process. Normally we check the allowed increase in price via maxIncreaseInPrice parameter in EditorConfig settings. In case this setting would allow to exceed limit value then this notHigherThenLimit validator takes its action on limit orders and do not allow to confirm sales-order above limit value

2020-10-15 14:55 UTC, ElaCzapiewska commented on src/client/components/SalesOrderEdit/i18n/de.json
> +    "SalesOrderEditForm.label.lineItems.validityPeriodEndDate": "Gültigkeitszeitraum Enddatum",
ok, all translation will be English only

2020-10-15 15:26 UTC, nczeranka requested changes

2020-10-15 15:26 UTC, nczeranka commented on src/server/api/Order.js
> +                            }
What happens, if the validity period end is already reached?
Don't we need an error handling? To be discussed with PM (Vesa).

2020-10-15 15:26 UTC, nczeranka commented on src/server/api/Order.js
> +            const today = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() ));
You can keep it simply. We are working only with UTC  on server side. (Only the UI is showing different time zones.)
Only for creation from via REST (e.g. from wM) we have to assure that the date is in UTC.

2020-10-15 15:26 UTC, nczeranka commented on src/server/api/Order.js
> +        }
Don't use LimitOrderItem specific fields for non-LimitOrdersItems. This is confusing.
E.g. switch the conditions: if (isLimitItem) ... else ...

2020-10-15 15:26 UTC, nczeranka commented on src/server/api/Order.js
> +
These values should be condition. So please include the check for the LimitOrder as the orderType.
Else it is confusing.

2020-10-15 15:26 UTC, nczeranka commented on src/server/api/Order.js
> +            item.totalNetPrice = item.quantity * item.netPrice / item.priceUnit;
Did you loose the confirmedTotelNetPrice for standardItems?

2020-10-15 16:07 UTC, ElaCzapiewska commented on src/shared/data/statusMapping.json
> +        "value": "partiallyInvoiced"
I am also confused with the key-values in this file, but before I added this one pair, the already confirmed sales order after partial invoicing received status "partially confirmed" that was definitely wrong state

2020-10-15 16:22 UTC, ElaCzapiewska commented on src/server/db/migrations/029-add-orderType-validityPeriod.main.js
> +        SET child.orderType = parent.type
draft, change, ... is going also to be update with this query, as every record (child) is looking for its parent, so the original order (or serviceOrder or limitOrder).

I also considered the solution you proposed, but the one I chose seemed to me more general, although probably it would also require creation of some indexes as the data volume in stage and prod is different then in local where I tested it

2020-10-15 16:26 UTC, ElaCzapiewska commented on src/server/db/migrations/029-add-orderType-validityPeriod.main.js
> +                                END
as for now we do not support AU, however every limit item is supposed to be expressed as such (Action Unit).

2020-10-22 09:28 UTC, ElaCzapiewska commented on src/client/components/SalesOrderEdit/i18n/de.json
> +    "SalesOrderEditForm.label.lineItems.limitValue": "Grenzwert",
removed

2020-10-23 14:03 UTC, jacekWojcikOpusCapita requested changes

2020-10-23 16:05 UTC, ElaCzapiewska commented on src/client/api/DespatchAdvice.js
> +                .map(item => {
corrected

2020-10-26 08:31 UTC, jacekWojcikOpusCapita approved these changes

2020-10-26 09:11 UTC, ElaCzapiewska commented on src/client/containers/i18n/de.json
> +    "Common.invoicedValue": "Rechnungswert",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/de.json
> +            "limitOrder": "Bestellung begrenzen"
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/es.json
> +    "Common.invoicedValue": "Invoiced value",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/es.json
> +    "SalesOrder.type.limitOrder": "Pedido de limite",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/fi.json
> +        "invoicedValue": "Invoiced value"
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/fi.json
> +            "limitOrder": "Rajajärjestys"
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/fr.json
> +    "Common.invoicedValue": "Invoiced value",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/fr.json
> +    "SalesOrder.type.limitOrder": "Ordre limite",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/it.json
> +    "Common.invoicedValue": "Invoiced value",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/it.json
> +    "SalesOrder.type.limitOrder": "Ordine limite",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/pl.json
> +    "Common.invoicedValue": "Wartość zafakturowana",
removed

2020-10-26 09:12 UTC, ElaCzapiewska commented on src/client/containers/i18n/pl.json
> +    "SalesOrder.type.limitOrder": "Blanket Order",
removed

2020-10-26 09:13 UTC, ElaCzapiewska commented on src/client/containers/i18n/pt.json
> +    "Common.invoicedValue": "Invoiced value",
removed

2020-10-26 09:13 UTC, ElaCzapiewska commented on src/client/containers/i18n/pt.json
> +    "SalesOrder.type.limitOrder": "Pedido de limite",
removed

2020-10-26 09:13 UTC, ElaCzapiewska commented on src/client/containers/i18n/sv.json
> +    "Common.invoicedValue": "Invoiced value",
removed

2020-10-26 09:13 UTC, ElaCzapiewska commented on src/client/containers/i18n/sv.json
> +            "limitOrder": "Begränsa Ordern"
removed

2020-10-26 09:14 UTC, ElaCzapiewska commented on src/server/db/models/SalesOrderItem.js
> +            type: Sequelize.ENUM('item', 'serviceItem', 'limitItem'),
ok, agreed with PM, standardOrder and standardItem namings are used

2020-10-26 09:15 UTC, ElaCzapiewska commented on src/shared/data/salesOrderTypes.json
> +        "order": "order",
ok, agreed with PM, standardOrder and standardItem namings are used

2020-10-26 09:15 UTC, ElaCzapiewska commented on src/shared/data/salesOrderTypes.json
> +        "item": "item",
ok, agreed with PM, standardOrder and standardItem namings are used

2020-10-26 09:16 UTC, ElaCzapiewska commented on src/server/db/migrations/029-add-orderType-validityPeriod.main.js
> +            and child.orderNumber = parent.orderNumber
ok, code removed as migration script changed

2020-10-26 09:21 UTC, ElaCzapiewska commented
requested changes have been addressed

2020-10-26 09:58 UTC, ElaCzapiewska commented
as Norbert is not available and the changes requested by him were addressed, I am merging the code as Jacek approved it

2020-10-26 10:04 UTC, merged